### ISSUE TITLE
vue3+vite 启动报错

### ISSUE THREAD

**Issue by XU1029** [lishaobos/magic-img#1]
Uncaught (in promise) Error: 需要 src

at MagicImg.connectedCallback (index.mjs:34:15)

at insert (runtime-dom.esm-bundler.js:10:16)

at mountElement (runtime-core.esm-bundler.js:5246:9)

at processElement (runtime-core.esm-bundler.js:5178:13)

at patch (runtime-core.esm-bundler.js:5098:21)

at mountChildren (runtime-core.esm-bundler.js:5285:13)

at processFragment (runtime-core.esm-bundler.js:5458:13)

at patch (runtime-core.esm-bundler.js:5094:17)

at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5638:21)

at [ReactiveEffect.run](http://link.zhihu.com/?target=http%3A//ReactiveEffect.run) (reactivity.esm-bundler.js:187:25)

**Comment by lishaobos** [comment]
请问可以提供可复现的 git 仓库吗

**Comment by lishaobos** [comment]
> Uncaught (in promise) Error: 需要 src
> 
> at MagicImg.connectedCallback (index.mjs:34:15)
> 
> at insert (runtime-dom.esm-bundler.js:10:16)
> 
> at mountElement (runtime-core.esm-bundler.js:5246:9)
> 
> at processElement (runtime-core.esm-bundler.js:5178:13)
> 
> at patch (runtime-core.esm-bundler.js:5098:21)
> 
> at mountChildren (runtime-core.esm-bundler.js:5285:13)
> 
> at processFragment (runtime-core.esm-bundler.js:5458:13)
> 
> at patch (runtime-core.esm-bundler.js:5094:17)
> 
> at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5638:21)
> 
> at [ReactiveEffect.run](http://link.zhihu.com/?target=http%3A//ReactiveEffect.run) (reactivity.esm-bundler.js:187:25)


ok 了，兄弟，使用最新版的 magic-img
